### ISSUE TITLE
Utilizing Fail2ban?

### ISSUE THREAD

**Issue by Vdragon** [Geniusking/OscarTool#1]
> Fail2ban monitors log files (e.g. /var/log/auth.log, /var/log/apache/access.log) and temporarily or persistently bans failure-prone addresses by updating existing firewall rules. Fail2ban allows easy specification of different actions to be taken such as to ban an IP using iptables or hostsdeny rules, or simply to send a notification email.

I believe this can be implemented using Fail2ban, any ideas?

**Comment by Geniusking** [comment]
Maybe Fail2ban can do that but it need to learn how to use that.
For me, If I know how to detect the attack, write a script to do that is more easily.
Thanks for your sharing.
